export default {
    sendmoney: 'Send Money',
    billpay: 'Bill Pay',
    gas:"Gas",
    electricity:"Electricity",
    water:"Water",
    tv:"TV",
    telephone:"Telephone",
    internet:"Internet",
    education:"Education",
    other:"Others",
    previouscontacts:'Previous Contacts',
    profilesuccess:'Your profile is completed',
    mobileno:'Mobile Number',
    password:'Password',
    forgotpin:'Forgot PIN',
    login:'Login',
    noaccount:"Don't have an account",
    confirmpin:'Confirm PIN',
    alreadyaccount:'Already have an account',
    termsagree:'I agree with the EPS Terms & Condition',
    viewprofile:'View Profile',
    passwordrequired:'Password is required',
    mobilenumberrequired:'Mobile number is required',
    pinrequired:'PIN number required',
    confirmpinrequired:'Confirm PIN required',
    networkerror:'Network Error!',
    networkerrorDetail:'Please check if your device has internet connectivity.',
    ok:'OK',
    continue:'CONTINUE',
    SEBL:'Southeast Bank Ltd.',
    IBBL:'Islami Bank Bangladesh Ltd',
    TBL:'Trust Bank Ltd',
    instant:'Instant',
    fundtransfer:'Fund Transfer',
    hasslefree:'Hassle free',
    billandfeesPayment:'Bill and Fees Payment',
    welcome:'Welcome to',
    epslifestyle:'EPS Lifestyle',
    next:'next',
     ////////////////////OTP//////////////////////
    otpmsg:'An OTP code will be sent to you to confirm this action',
    otpnomsg:' Enter the 6 digit OTP to proceed',
    ////////////////////Send Money form//////////////////////
    senderaccount:"SENDER'S ACCOUNT",
    receiveraccount:"RECEIVER'S ACCOUNT",
    bybank:'By Bank Account',
    byeps:'By EPS Account',
    receiverbank:'Receiver Bank',
    bankbranch:'Bank Branch',
    routingno:'Routing Number',
    accountname:'Account Name',
    accountno:'Account Number',
    BDT:'BDT',
    notemsg:'Enter note to specify your transaction',
    note: 'Note',
    receivermobileno:'Receiver Mobile No',
    selectreceiveraccount:'Select Receiver Account',
    amount:'Amount',
 ///New Register////
    mobilenum:'Mobile Number',
    pin:'PIN',
     
    profile:'Profile',
    perinfo:'Personal Info',
     name:'Name',
     email:'Email',
     nid:'NID',
     nationalidentity:'National Identity',
     explain:'Take a picture of your goverment issued NID card(Form front and back)to verify your identity',
     fs:'Front Side',
     bs:'Back Side',
   
     profile:'Profile',
     yourphoto:'Your Photo',
     takephoto:'Take Photo',

     procomplete:'your is profile completed  .',
     home:'হোম ',
    
    heading:' Please add your Bank Account to activate Send Money.',
    addbank:'Add Bank',
    seeall:'See All',
    exlist:'Existing List',
    ///History////
    transactionhistory:'Transaction History',
    startdate:'Start Date',
    enddate:'End Date',
    search:'Search',
    transactions:'Transactions',
    all:'All',
    in:'In',
    out:'Out',
    id:'ID',
    bank:'Bank',
    transactionsid:'Transaction ID',
    from:'From',
    to:'To',
    notepersonal:'I send money  for my home personal',
    downloadrecp:'Download Receipt',
    ////profile///
    linkbankacc:'LINKED BANK ACCOUNTS',
    setlimit:'SET LIMIT',
    setting:'SETTINGS',
    contus:'CONTACT US',
    helpfaq:'HELP & FAQS',
    selectbank:'Select Bank',
    bankaccnum:'Bank Account Number',
    bankroutingnum:'Bank Routing Number',
    letcon:'Let’s connect your Bank Account',
    successfully:'You have Successfully connected your [*Bank Name*] Account to EPS System',
    otp:'OTP',
    done:'Done',
    logout:'Log-Out',
    changepin:'Change Pin',
    oldpin:'Old Pin',
    newpin:'New Pin',
    renewpin:'Retype New Pin',
    changepinsave:'CHANGE PIN SAVE',
    yourpinsucc:'Your Pin has Changed Successfully',
    /////payBill///
    higdmorn:'Hi Good Morning',
    billorg:'Select Bill Organizations',
    billperiod:'Bill Period',
    entersmsnum:'Enter SMS Account Number',
    savebillinfo:'Save Bill Info to Pay Bill easily',
    payprocess:'Process To Pay',
    myaccount:'My Account',
    billpayto:'Bill Pay To',
    charge:'Charge',
    totalamount:'Total Amount',
    smsaccount:'SMS Account Number',
    duedate:'Due Date',
    status:'Status',
    ref:'Reference',
    tap:'Tap & Hold to Send Money',
    congratulation:'Congratulations',
    successfullypaybill:'Successfully pay your bill',
    backhome:'Back To Home',


  

    











  };