export default {
    sendmoney: 'টাকা পাঠান',
    billpay: 'বিল পরিশোধ',
    gas: "গ্যাস",
    electricity: "বিদ্যুৎ",
    water: "পানি",
    tv: "টেলিভিশন",
    telephone:"টেলিফোন",
    internet: "ইন্টারনেট",
    education:"শিক্ষা",
    other:"অন্যান্য",
    previouscontacts:'পূর্ববর্তী পরিচিতি',
    profilesuccess:'অভিনন্দন! আপনি সফলভাবে আপনার প্রোফাইল সম্পূর্ণ করেছেন',
    mobileno:'মোবাইল নম্বরঃ',
    password:'পাসওয়ার্ড',
    forgotpin:'PIN ভুলে গিয়েছেন',
    login:'লগ-ইন',
    signup:'সাইন-আপ',
    noaccount:'অ্যাকাউন্ট করা হয়নি',
    confirmpin:'PIN নিশ্চিত করুন',
    alreadyaccount:'ইতিমধ্যে একটি অ্যাকাউন্ট আছে',
    termsagree:'আমি EPS শর্তাবলীর সাথে সম্মতি পোষণ করছি',
    viewprofile:'প্রোফাইল দেখুন',
    passwordrequired:'পাসওয়ার্ড প্রয়োজন',
    mobilenumberrequired:'মোবাইল নম্বর প্রয়োজন',
    pinrequired:'PIN নম্বর প্রয়োজন',
    confirmpinrequired:'PIN নম্বর নিশ্চিত করা প্রয়োজন',
    networkerror:'নেটওয়ার্ক ত্রুটি!',
    networkerrorDetail:'আপনার ডিভাইসে ইন্টারনেট সংযোগ চেক করুন।',
    ok:'ঠিক আসে',
    continue:'পরবর্তী',
    SEBL:'সাউথ ইস্ট ব্যাংক লিমিটেড',
    IBBL:'ইসলামিক ব্যাংক লিমিটেড',
    TBL:'ট্রাস্ট ব্যাংক লিমিটেড',
    instant:'ইনস্ট্যান্ট',
    fundtransfer:'ফান্ড ট্রান্সফার',
    hasslefree:'ঝামেলামুক্ত',
    billandfeesPayment:'বিল ও ফি পরিশোধ',
    welcome:'স্বাগতম',
    epslifestyle:'EPS লাইফস্টাইলে',
    next:'পরবর্তী ধাপ',
    otpmsg:'নিশ্চিত করার জন্য আপনাকে একটি OTP কোড পাঠানো হবে।',
    otpnomsg:'পরবর্তী ধাপে যেতে 6 সংখ্যার OTP নম্বরটি লিখুন',
      ////////////////////Send Money form//////////////////////
    senderaccount:'প্রেরকের একাউন্ট',
    receiveraccount:"প্রাপকের অ্যাকাউন্ট",
    bybank:'ব্যাংক অ্যাকাউন্টের মাধ্যমে',
    byeps:'EPS অ্যাকাউন্টের মাধ্যমে ',
    receiverbank:'প্রাপকের ব্যাঙ্ক',
    bankbranch:'ব্যাংক ব্রাঞ্চ',
    routingno:'রাউটিং নম্বর',
    accountname:'অ্যাকাউন্ট নাম',
    accountno:'অ্যাকাউন্ট নম্বর',
    BDT:'টাকা',
    notemsg:'আপনার লেনদেনের নোট লিখুন',
    note: 'নোট',
    receivermobileno:'প্রাপকের মোবাইল নম্বর',
    selectreceiveraccount:'প্রাপকের অ্যাকাউন্ট বাছাই করুন',
    amount:'টাকার পরিমাণ',
    ///New Register////
     mobilenum:'মোবাইল নম্বর',
    pin:'PIN',
    ////ADD Profile////
    profile:'প্রোফাইল',
    perinfo:'ব্যাক্তিগত তথ্য,',
    name:'নাম',
    email:'ই-মেইল',
    nid:'এনআইডি ',
    nationalidentity:'National Identity',
    explain:'আপনার পরিচয় যাচাই করার জন্য সরকার কর্তৃক জারি কৃত NID কার্ডের (সামনে থেকে এবং পিছন থেকে) ছবি তুলুন।',
    fs:'সামনের দিক',
    bs:'পিছনের দিক',
     ////profile///
    yourphoto:'আপনার ছবি',
    takephoto:'ছবি তুলুন',
    procomplete:'আপনার প্রোফাইল সম্পূর্ণ করেছেন.',
    backhome:'হোম ',
    heading:' সেন্ড মানি সক্রিয় করতে অনুগ্রহ করে আপনার ব্যাংক অ্যাকাউন্ট যোগ করুন.',
    seeall:'সব দেখুন',
    exlist:'বিদ্যমান তালিকা',
    ///History////
    transactionhistory:'পূর্বের লেনদেন',
    startdate:'শুরুর তারিখ',
    enddate:'শেষের তারিখ',
    search:'অনুসন্ধান করুন',
    transactions:'লেনদেন',
    all:'সব',
    in:'ভিতরে',
    out:'আউট',
    id:'আইডি',
    bank:'ব্যাংক',
    transactionsid:'লেনদেন নম্বর',
    from:'থেকে',
    to:'প্রতি',
    note:'বিঃদ্রঃআমি আমার বাড়ির জন্য টাকা পাঠাই',
    download:'রসিদ ডাউনলোড করুন',
 ////profile///
    linkbankacc:'সংযুক্ত ব্যাংক অ্যাকাউন্ট সমূহ',
    setlimit:'সীমা সেট করুন',
    setting:'সেটিংস',
    contus:'যোগাযোগ করুন',
    helpfaq:'সাহায্য এবং FAQ’s',
    selectbank:'ব্যাংক বাছাই করুন',
    bankaccnum:'ব্যাংক অ্যাকাউন্ট নম্বর',
    bankroutingnum:'ব্যাংক রাউটিং নম্বর',
    letcon:'আপনার ব্যাংক অ্যাকাউন্ট সংযুক্ত করুন',
    successfully:'আপনি সফলভাবে আপনার [*Bank Name*] অ্যাকাউন্ট EPS সিস্টেমের সাথে সংযুক্ত করেছেন',
    otp:'OTP',
    done:'Done',
    logout:'Log-Out',
    changepin:'পিন পরিবর্তন করুন',
    oldpin:'পুরাতন পিন',
    newpin:'নতুন পিন',
    renewpin:'নতুন পিন পুনরায় টাইপ করুন',
    changepinsave:'পরিবর্তন পিন সেভ  করুন',
    yourpinsucc:'আপনার পিন সফলভাবে পরিবর্তিত হয়েছে',
    /////payBill///
    higdmorn:'হ্যালো, শুভ সকাল',
    billorg:'বিল সংস্থা নির্বাচন করুন',
    billperiod:'বিলের সময়কাল',
    entersmsnum:'এসএমএস অ্যাকাউন্ট নম্বর লিখুন',
    savebillinfo:'সহজেই বিল পরিশোধ করতে বিলের তথ্য সংরক্ষণ করুন',
    payprocess:'অর্থ প্রদানের প্রক্রিয়া',
    myaccount:'আমার অ্যাকাউন্ট',
    billpayto:'বিল দিতে',
    charge:'চার্জ',
    totalamount:'সর্বমোট পরিমাণ',
    smsaccount:'এসএমএস অ্যাকাউন্ট নম্বর',
    duedate:'নির্দিষ্ট তারিখ',
    status:'স্ট্যাটাস',
    ref:'রেফারেন্স',
    tap:'টাকা পাঠাতে ট্যাপ করে ধরে থাকুন',
    congratulation:'অভিনন্দন',
    successfullypaybill:'সফলভাবে আপনার বিল পরিশোধ  হয়েছে',
    backhome:'বাড়িতে ফিরে যাও',

    





   
  };
  
